---
# This playbook deploys a simple Tomcat 7 cluster behind an HAProxy. 

- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:
    - common

- hosts: tomcat-servers 
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:
    - tomcat
    - webapp

- hosts: lbservers
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:
    - haproxy
